local wk = require("which-key")
local tablex = require("pl.tablex")
-- Surround-related mappings
wk.register({
  s = {
    name = "surround",
    ["t"] = "Surrounding <tag>...</tag>",
    ['"'] = 'Surrounding "..."',
    ["'"] = "Surrounding '...'",
    ["`"] = "Surrounding `...`",
    ["("] = "Surrounding ( ... )",
    [")"] = "Surrounding (...)",
    ["b"] = "Surrounding (...)",
    ["{"] = "Surrounding { ... }",
    ["}"] = "Surrounding {...}",
    ["B"] = "Surrounding {...}",
    ["["] = "Surrounding [ ... ]",
    ["]"] = "Surrounding [...]",
    ["r"] = "Surrounding [...]",
    [">"] = "Surrounding <...>",
    ["a"] = "Surrounding <...>",
  },
}, {
  prefix = "d",
})
local creations = {
  ['"'] = 'Surround with "..."',
  ["'"] = "Surround with '...'",
  ["`"] = "Surround with `...`",
  ["("] = "Surround with ( ... )",
  [")"] = "Surround with (...)",
  ["b"] = "Surround with (...)",
  ["{"] = "Surround with { ... }",
  ["}"] = "Surround with {...}",
  ["B"] = "Surround with {...}",
  ["["] = "Surround with [ ... ]",
  ["]"] = "Surround with [...]",
  ["r"] = "Surround with [...]",
  [">"] = "Surround with <...>",
  ["a"] = "Surround with <...>",
}
local replacements = {
  ['"'] = 'Change to "..."',
  ["'"] = "Change to '...'",
  ["`"] = "Change to `...`",
  ["("] = "Change to ( ... )",
  [")"] = "Change to (...)",
  ["b"] = "Change to (...)",
  ["{"] = "Change to { ... }",
  ["}"] = "Change to {...}",
  ["B"] = "Change to {...}",
  ["["] = "Change to [ ... ]",
  ["]"] = "Change to [...]",
  ["r"] = "Change to [...]",
  [">"] = "Change to <...>",
  ["a"] = "Change to <...>",
}
wk.register({
  s = {
    name = "surround",
    ["w"] = tablex.union({ name = "Create surrounding word" }, creations),
    ["W"] = tablex.union({ name = "Create surrounding WORD" }, creations),
    ["s"] = tablex.union({ name = "Create surrounding sentence" }, creations),
    ["p"] = tablex.union({ name = "Create surrounding paragraph" }, creations),
    ["t"] = tablex.union({ name = "Change surrounding <tag>...</tag>" }, replacements),
    ['"'] = tablex.union({ name = 'Change surrounding "..."' }, replacements),
    ["'"] = tablex.union({ name = "Change surrounding '...'" }, replacements),
    ["`"] = tablex.union({ name = "Change surrounding `...`" }, replacements),
    ["("] = tablex.union({ name = "Change surrounding ( ... )" }, replacements),
    [")"] = tablex.union({ name = "Change surrounding (...)" }, replacements),
    ["b"] = tablex.union({ name = "Change surrounding (...)" }, replacements),
    ["{"] = tablex.union({ name = "Change surrounding { ... }" }, replacements),
    ["}"] = tablex.union({ name = "Change surrounding {...}" }, replacements),
    ["B"] = tablex.union({ name = "Change surrounding {...}" }, replacements),
    ["["] = tablex.union({ name = "Change surrounding [ ... ]" }, replacements),
    ["]"] = tablex.union({ name = "Change surrounding [...]" }, replacements),
    ["r"] = tablex.union({ name = "Change surrounding [...]" }, replacements),
    [">"] = tablex.union({ name = "Change surrounding <...>" }, replacements),
    ["a"] = tablex.union({ name = "Change surrounding <...>" }, replacements),
  },
  S = {
    name = "surround-line",
    ["w"] = tablex.union({ name = "Create surrounding word" }, creations),
    ["W"] = tablex.union({ name = "Create surrounding WORD" }, creations),
    ["s"] = tablex.union({ name = "Create surrounding sentence" }, creations),
    ["p"] = tablex.union({ name = "Create surrounding paragraph" }, creations),
    ["t"] = tablex.union({ name = "Change surrounding <tag>...</tag>" }, replacements),
    ['"'] = tablex.union({ name = 'Change surrounding "..."' }, replacements),
    ["'"] = tablex.union({ name = "Change surrounding '...'" }, replacements),
    ["`"] = tablex.union({ name = "Change surrounding `...`" }, replacements),
    ["("] = tablex.union({ name = "Change surrounding ( ... )" }, replacements),
    [")"] = tablex.union({ name = "Change surrounding (...)" }, replacements),
    ["b"] = tablex.union({ name = "Change surrounding (...)" }, replacements),
    ["{"] = tablex.union({ name = "Change surrounding { ... }" }, replacements),
    ["}"] = tablex.union({ name = "Change surrounding {...}" }, replacements),
    ["B"] = tablex.union({ name = "Change surrounding {...}" }, replacements),
    ["["] = tablex.union({ name = "Change surrounding [ ... ]" }, replacements),
    ["]"] = tablex.union({ name = "Change surrounding [...]" }, replacements),
    ["r"] = tablex.union({ name = "Change surrounding [...]" }, replacements),
    [">"] = tablex.union({ name = "Change surrounding <...>" }, replacements),
    ["a"] = tablex.union({ name = "Change surrounding <...>" }, replacements),
  },
}, {
  prefix = "c",
})
