# This has been optimized for minimized maintainence, runtime performance, and
# file size. Readability was not a prioroty.

if [[ -o 'aliases' ]]; then
  'builtin' 'unsetopt' 'aliases'
  local p10k_lean_restore_aliases=1
else
  local p10k_lean_restore_aliases=0
fi

() {
  emulate -L zsh
  setopt no_unset

  unset -m 'POWERLEVEL9K_*'

  # Prompt segments
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=( os_icon dir vcs prompt_char )
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=( status command_execution_time background_jobs virtualenv pyenv context time )
  # Universal config
  typeset -gH POWERLEVEL9K_BACKGROUND= POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE= POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' ' POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR= POWERLEVEL9K_MODE=nerdfont-complete POWERLEVEL9K_ICON_BEFORE_CONTENT=true POWERLEVEL9K_PROMPT_ADD_NEWLINE=false POWERLEVEL9K_SHOW_RULER=false
  # os_icon: os identifier
  typeset -gHi POWERLEVEL9K_OS_ICON_FOREGROUND=212
  # prompt_char: prompt symbol
  typeset -gHi POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS}_FOREGROUND=76 POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS}_FOREGROUND=196
  typeset -gH POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯' POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮' POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='Ⅴ' POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
  # dir: current directory
  typeset -gHi POWERLEVEL9K_DIR_FOREGROUND=31 POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=103 POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=39 POWERLEVEL9K_SHORTEN_DIR_LENGTH=1 POWERLEVEL9K_DIR_MAX_LENGTH=80
  typeset -gH POWERLEVEL9K_DIR_CLASSES=()
  typeset -gH POWERLEVEL9K_SHORTEN_STRATEGY=truncate_from_right POWERLEVEL9K_SHORTEN_DELIMITER= POWERLEVEL9K_DIR_ANCHOR_BOLD=true POWERLEVEL9K_DIR_HYPERLINK=false POWERLEVEL9K_DIR_SHOW_WRITABLE=true
  # vcs: git status
  local vcs='${${VCS_STATUS_LOCAL_BRANCH:+%76F${(g::)POWERLEVEL9K_VCS_BRANCH_ICON}${VCS_STATUS_LOCAL_BRANCH//\%/%%}}:-%f@%76F${VCS_STATUS_COMMIT[1,8]}}${${VCS_STATUS_REMOTE_BRANCH:#$VCS_STATUS_LOCAL_BRANCH}:+%f:%76F${VCS_STATUS_REMOTE_BRANCH//\%/%%}}${VCS_STATUS_TAG:+%f#%76F${VCS_STATUS_TAG//\%/%%}}${${VCS_STATUS_COMMITS_BEHIND:#0}:+ %76F⇣${VCS_STATUS_COMMITS_BEHIND}}${${VCS_STATUS_COMMITS_AHEAD:#0}:+${${(M)VCS_STATUS_COMMITS_BEHIND:#0}:+ }%76F⇡${VCS_STATUS_COMMITS_AHEAD}}${${VCS_STATUS_STASHES:#0}:+ %76F*${VCS_STATUS_STASHES}}${VCS_STATUS_ACTION:+ %196F${VCS_STATUS_ACTION//\%/%%}}${${VCS_STATUS_NUM_CONFLICTED:#0}:+ %196F~${VCS_STATUS_NUM_CONFLICTED}}${${VCS_STATUS_NUM_STAGED:#0}:+ %227F+${VCS_STATUS_NUM_STAGED}}${${VCS_STATUS_NUM_UNSTAGED:#0}:+ %227F!${VCS_STATUS_NUM_UNSTAGED}}${${VCS_STATUS_NUM_UNTRACKED:#0}:+ %39F?${VCS_STATUS_NUM_UNTRACKED}}'
  vcs="\${P9K_CONTENT:-$vcs}"
  typeset -gHi POWERLEVEL9K_VCS_LOADING_FOREGROUND=244 POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED,COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=-1 POWERLEVEL9K_VCS_{CLEAN,MODIFIED,UNTRACKED}_FOREGROUND=76
  typeset -gHaU POWERLEVEL9K_VCS_BACKENDS=(git)
  typeset -gH POWERLEVEL9K_VCS_BRANCH_ICON='' POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION= POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON=':' POWERLEVEL9K_VCS_COMMIT_ICON='@' POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='⇣' POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='⇡' POWERLEVEL9K_VCS_STASH_ICON='*' POWERLEVEL9K_VCS_TAG_ICON=$'%{\b#%}' POWERLEVEL9K_VCS_UNTRACKED_ICON=$'%{\b?%}' POWERLEVEL9K_VCS_UNSTAGED_ICON=$'%{\b!%}' POWERLEVEL9K_VCS_STAGED_ICON=$'%{\b+%}'
  typeset -gH POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_CONTENT_EXPANSION=$vcs
  typeset -gH POWERLEVEL9K_VCS_LOADING_CONTENT_EXPANSION=${${vcs//\%f}//\%<->F}
  # status: exit code of the last command
  typeset -gHi POWERLEVEL9K_STATUS_OK_FOREGROUND=70 POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=70 POWERLEVEL9K_STATUS_ERROR_FOREGROUND=160 POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=160 POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=160
  typeset -gH POWERLEVEL9K_STATUS_EXTENDED_STATES=true POWERLEVEL9K_STATUS_OK=false POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔' POWERLEVEL9K_STATUS_OK_PIPE=true POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='✔' POWERLEVEL9K_STATUS_ERROR=false POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='↵' POWERLEVEL9K_STATUS_ERROR_SIGNAL=true POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='↵' POWERLEVEL9K_STATUS_ERROR_PIPE=true POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='↵'
  # command_execution_time: duration of the last command
  typeset -gHi POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3 POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0 POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=101
  typeset -gH POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s' POWERLEVEL9K_COMMAND_EXECUTION_TIME_VISUAL_IDENTIFIER_EXPANSION=
  # background_jobs: presence of background jobs
  typeset -gHi POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=70
  typeset -gH POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_EXPANSION='${P9K_VISUAL_IDENTIFIER// }'
  # context: user@host
  typeset -gHi POWERLEVEL9K_CONTEXT_FOREGROUND=180 POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=227
  typeset -gH POWERLEVEL9K_CONTEXT_{ROOT_,}TEMPLATE='%n@%m' POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION= POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true
  # virtualenv: python virtual environment
  typeset -gHi POWERLEVEL9K_VIRTUALENV_FOREGROUND=37
  typeset -gH POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=
  # pyenv: python environment
  typeset -gHi POWERLEVEL9K_PYENV_FOREGROUND=37
  typeset -gH POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=false
  # time: current time
  typeset -gHi POWERLEVEL9K_TIME_FOREGROUND=66
  typeset -gH POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}' POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION=
}

(( ! p10k_lean_restore_aliases )) || setopt aliases
'builtin' 'unset' 'p10k_lean_restore_aliases'

# vim:ft=zsh:tw=80
