complete -c bingrep -l color -d "Forces coloring, even in files and pipes"
complete -c bingrep -s d -l debug -d "Print debug version of parse results"
complete -c bingrep -s D -l demangle -d "Apply Rust/C++ demangling"
complete -c bingrep -s h -l help -d "Prints help information"
complete -c bingrep -l hex -d "Print a colored and semantically tagged hex table"
complete -c bingrep -l ranges -d "Print a high level overview of the file offset ranges in this binary"
complete -c bingrep -s V -l version -d "Prints version information"
complete -xc bingrep -l extract -d "Extract from an archive the object file which contains the given symbol"
complete -xc bingrep -s s -l search -d "Search for string"
complete -xc bingrep -s t -l truncate -d "Truncate string results to X characters [default: 2048]"
