complete -c cut -x -s b -l bytes -d "Select only these bytes"
complete -c cut -x -s c -l characters -d "Select only these characters"
complete -c cut -x -s d -l delimiter -d "Use DELIM instead of TAB for field delimiter"
complete -c cut -x -s f -l fields -d "Select  only  these  fields"
complete -c cut -s n -d "Don't split multibyte characters" -n "__fish_contains_opt -s b bytes"
complete -c cut -l conplement -d "Complement the set of selected bytes, characters or fields"
complete -c cut -s s -l only-delimited -d "Don't print lines not containing delimiters"
complete -c cut -x -l output-delimiter -d "Use STRING as the output delimiter"
complete -c cut -s z -l zero-terminated -d "Line delimiter is NUL, not newline"
complete -c cut -l help -d "Display help & exit"
complete -c cut -l version -d "Display version & exit"
