# rclone completion
# this is nowhere near completion
set -l subcmd __fish_use_subcommand

# subcommands
complete -xc rclone -n "$subcmd" -a about -d "Get quota information from the remote"
complete -xc rclone -n "$subcmd" -a authorize -d "Remote authorization"
complete -xc rclone -n "$subcmd" -a cachestats -d "Print cache stats for a remote"
complete -xc rclone -n "$subcmd" -a cat -d "Concatenates any files and sends them to stdout"
complete -xc rclone -n "$subcmd" -a check -d "Checks the files in the source and destination match"
complete -xc rclone -n "$subcmd" -a cleanup -d "Clean up the remote if possible"
complete -xc rclone -n "$subcmd" -a config -d "Enter an interactive configuration session"
complete -xc rclone -n "$subcmd" -a copy -d "Copy files from source to dest, skipping already copied"
complete -xc rclone -n "$subcmd" -a copyto -d "Copy files from source to dest, skipping already copied"
complete -xc rclone -n "$subcmd" -a copyurl -d "Copy url content to dest"
complete -xc rclone -n "$subcmd" -a cryptcheck -d "Cryptcheck checks the integrity of a crypted remote"
complete -xc rclone -n "$subcmd" -a cryptdecode -d "Cryptdecode returns unencrypted file names"
complete -xc rclone -n "$subcmd" -a dbhashsum -d "Produces a Dropbox hash file for all the objects in the path"
complete -xc rclone -n "$subcmd" -a dedupe -d "Interactively find duplicate files and delete/rename them"
complete -xc rclone -n "$subcmd" -a delete -d "Remove the contents of path"
complete -xc rclone -n "$subcmd" -a deletefile -d "Remove a single file from remote"
complete -xc rclone -n "$subcmd" -a genautocomplete -d "Output completion script for a given shell" # this is currently useless
complete -xc rclone -n "$subcmd" -a gendocs -d "Output markdown docs for rclone to the directory supplied"
complete -xc rclone -n "$subcmd" -a hashsum -d "Produces an hashsum file for all the objects in the path"
complete -xc rclone -n "$subcmd" -a help -d "Show help for rclone commands, flags and backends"
complete -xc rclone -n "$subcmd" -a link -d "Generate public link to file/folder"
complete -xc rclone -n "$subcmd" -a listremotes -d "List all the remotes in the config file"
complete -xc rclone -n "$subcmd" -a ls -d "List the objects in the path with size and path"
complete -xc rclone -n "$subcmd" -a lsd -d "List all directories/containers/buckets in the path"
complete -xc rclone -n "$subcmd" -a lsf -d "List directories and objects in remote:path formatted for parsing"
complete -xc rclone -n "$subcmd" -a lsjson -d "List directories and objects in the path in JSON format"
complete -xc rclone -n "$subcmd" -a lsl -d "List the objects in path with modification time, size and path"
complete -xc rclone -n "$subcmd" -a md5sum -d "Produces an md5sum file for all the objects in the path"
complete -xc rclone -n "$subcmd" -a mkdir -d "Make the path if it doesn't already exist"
complete -xc rclone -n "$subcmd" -a mount -d "Mount the remote as file system on a mountpoint"
complete -xc rclone -n "$subcmd" -a move -d "Move files from source to dest"
complete -xc rclone -n "$subcmd" -a moveto -d "Move file or directory from source to dest"
complete -xc rclone -n "$subcmd" -a ncdu -d "Explore a remote with a text based user interface"
complete -xc rclone -n "$subcmd" -a obscure -d "Obscure password for use in the rclone.conf"
complete -xc rclone -n "$subcmd" -a purge -d "Remove the path and all of its contents"
complete -xc rclone -n "$subcmd" -a rc -d "Run a command against a running rclone"
complete -xc rclone -n "$subcmd" -a rcat -d "Copies standard input to file on remote"
complete -xc rclone -n "$subcmd" -a rcd -d "Run rclone listening to remote control commands only"
complete -xc rclone -n "$subcmd" -a rmdir -d "Remove the path if empty"
complete -xc rclone -n "$subcmd" -a rmdirs -d "Remove empty directories under the path"
complete -xc rclone -n "$subcmd" -a serve -d "Serve a remote over a protocol"
complete -xc rclone -n "$subcmd" -a settier -d "Changes storage class/tier of objects in remote"
complete -xc rclone -n "$subcmd" -a sha1sum -d "Produces an sha1sum file for all the objects in the path"
complete -xc rclone -n "$subcmd" -a size -d "Prints the total size and number of objects in remote:path"
complete -xc rclone -n "$subcmd" -a sync -d "Make source and dest identical, modifying destination only"
complete -xc rclone -n "$subcmd" -a touch -d "Create new file or change file modification time"
complete -xc rclone -n "$subcmd" -a tree -d "List the contents of the remote in a tree like fashion"
complete -xc rclone -n "$subcmd" -a version -d "Show the version number"
