complete -c rpatool -xa '(__fish_complete_suffix .rpa)'

complete -c rpatool -s l -l list -d "List files in archive"
complete -c rpatool -s x -l extract -d "Extract files from archive"
complete -c rpatool -s c -l create -d "Create archive from files"
complete -c rpatool -s d -l delete -d "Delete files from archive"
complete -c rpatool -s a -l append -d "Append files to archive"
complete -c rpatool -s 2 -l two -d "Use RPAv2 format"
complete -c rpatool -s 3 -l three -d "Use RPAv3 format"
complete -xc rpatool -s k -l key -d "Obfuscation key for archive"
complete -xc rpatool -s p -l padding -d "Max number of padding bytes"
complete -rc rpatool -s o -l outfile -d "Alternative output archive file"
complete -c rpatool -s h -l help -d "Display help & exit"
complete -c rpatool -s v -l verbose -d "Be verbose"
complete -c rpatool -s V -l version -d "Show version info"
