# systemd-cgtop
complete -fc systemd-cgtop -a '(systemd-cgtop -1b | string match -r "^\S+")'

complete -c systemd-cgtop -s h -l help -d 'Print a short help text and exit'
complete -c systemd-cgtop -l version -d 'Print a short version string and exit'

# complete -c systemd-cgtop -l order -d 'Order by' -a 'path tasks cpu memory io'
complete -c systemd-cgtop -s p -l order=path -d 'Order by control group path name'
complete -c systemd-cgtop -s t -l order=tasks -d 'Order by number of tasks/processes in the control group'
complete -c systemd-cgtop -s c -l order=cpu -d 'Order by CPU load'
complete -c systemd-cgtop -s m -l order=memory -d 'Order by memory usage'
complete -c systemd-cgtop -s i -l order=io -d 'Order by disk I/O load'
complete -c systemd-cgtop -s b -l batch -d 'Run in batch mode, accepting no input'
complete -c systemd-cgtop -s r -l raw -d 'Format byte counts (as in memory usage and I/O metrics) and CPU time with raw…'
complete -c systemd-cgtop -l cpu -d 'Controls whether CPU usage is shown as percentage or time' -a 'percentage time'
complete -c systemd-cgtop -s P -d 'Count only userspace processes instead of all tasks'
complete -c systemd-cgtop -s k -d 'Count only userspace processes and kernel threads instead of all tasks'
complete -c systemd-cgtop -l recursive -d 'Sum up process count recursively'
complete -c systemd-cgtop -s n -l iterations -x -d 'Perform only this many iterations'
complete -c systemd-cgtop -s 1 -d 'A shortcut for --iterations=1'
complete -c systemd-cgtop -s d -l delay -x -d 'Specify refresh delay in seconds (or if one of "ms", "us", "min" is specified…'
complete -c systemd-cgtop -l depth -x -d 'Maximum control group tree traversal depth (default: 3)'
complete -c systemd-cgtop -s M -l machine -x -d 'Limit control groups shown to the part corresponding to the container MACHINE'
