return {
  -- Technically you can change almost anything, but for some things IMO you probably shouldn't.
  read_globals = {
    'deploy_bin_dir',
    'deploy_lib_dir',
    'deploy_lua_dir',
    lua_found = {fields = {'lua_bindir', 'lua_dir', 'lua_interpreter', 'lua_version'}},
    'major_version',
    'program_series',
    'program_version',
    'user_agent',
    cache = {fields = {'luajit_version_checked'}},
  },
  globals = {
    'dump_env',
    'os_getenv',
    'lua_version',
    'home',
    'platforms',
    'processor',
    'target_cpu',
    'arch',
    'export_path_separator',
    'lua_interpreter',
    'local_by_default',
    'accept_unknown_fields',
    'fs_use_modules',
    'hooks_enabled',
    'deps_mode',
    'no_manifest',
    'check_certificates',
    'cache_timeout',
    'cache_fail_timeout',
    'lua_modules_path',
    'lib_modules_path',
    'rocks_subdir',
    'lib_extension',
    'obj_extension',
    'link_lua_explicitly',
    'rocks_servers',
    'disabled_servers',
    upload = {fields = {'server', 'tool_version', 'api_version'}},
    'lua_extension',
    'connection_timeout',
    variables = {
      other_fields = true,
      fields = {
        'LUA', 'LUALIB', 'LUA_DIR', 'LUA_BINDIR', 'LUA_LIBDIR', 'LUA_INCDIR', 'LUA_LIBDIR_FILE',
        'MAKE', 'CC', 'LD', 'AR', 'RANLIB', 'RC', 'MT', 'CVS', 'GIT', 'SSCM', 'SVN', 'HG', 'RSYNC',
        'RSYNCFLAGS', 'SCP', 'WGET', 'WGETNOCERTFLAG', 'CURL', 'CURLNOCERTFLAG', 'PWD', 'MKDIR',
        'RMDIR', 'CP', 'LS', 'RM', 'FIND', 'TEST', 'CHMOD', 'ICACLS', 'MKTEMP', 'STAT', 'ZIP',
        'UNZIP', 'GUNZIP', 'BUNZIP2', 'TAR', 'MD5SUM', 'OPENSSL', 'MD5', 'TOUCH', 'CMAKE', 'SEVENZ',
        'CFLAGS', 'LIBFLAG', 'LIB_EXTENSION', 'OBJ_EXTENSION', 'ROCKS_TREE', 'SCRIPTS_DIR',
      },
    },
    external_deps_subdirs = {fields = {'bin', 'lib', 'include'}},
    runtime_external_deps_subdirs = {fields = {'bin', 'lib', 'include'}},
    'external_lib_extension',
    'static_lib_extension',
    'external_deps_dirs',
    'makefile',
    'wrapper_suffix',
    'local_cache',
    'web_browser',
    'cmake_generator',
    external_deps_patterns = {fields = {'bin', 'lib', 'include'}},
    runtime_external_deps_patterns = {fields = {'bin', 'lib', 'include'}},
    'gcc_rpath',
    'use_extensions',
    'home_tree',
    'homeconfdir',
    'sysconfdir',
    'rocks_trees',
    'check_certificates',
  },
}
