-- Standalone ALE config
vim.g.ale_fix_on_save = false
vim.g.ale_disable_lsp = true
vim.g.ale_linters_ignore = {
  ada = {'gcc'},
  asciidoc = {'alex', 'languagetool', 'proselint', 'redpen', 'textlint', 'vale', 'writegood'},
  asm = {'gcc'},
  bats = {'shellcheck'},
  c = {'cc', 'clangtidy', 'cppcheck', 'cpplint', 'flawfinder', 'gcc'},
  cmake = {'cmakelint'},
  cpp = {'cc', 'clangcheck', 'clangtidy', 'cppcheck', 'cpplint', 'flawfinder', 'gcc'},
  cs = {'mcs'},
  css = {'csslint', 'fecs', 'stylelint'},
  dockerfile = {'hadolint'},
  elixir = {'credo'},
  eruby = {'erb'},
  fish = {'fish'},
  fortran = {'gcc'},
  fountain = {'proselint'},
  gitcommit = {'gitlint'},
  graphql = {'eslint'},
  help = {'alex', 'proselint', 'writegood'},
  html = {'alex', 'fecs', 'htmlhint', 'proselint', 'stylelint', 'tidy', 'writegood'},
  javascript = {'eslint', 'fecs', 'flow', 'jscs', 'jshint', 'standard', 'xo'},
  json = {'jsonlint', 'jq', 'spectral'},
  less = {'stylelint'},
  lua = {'luacheck', 'luac'},
  mail = {'alex', 'languagetool', 'proselint', 'vale'},
  markdown = {
    'alex', 'languagetool', 'markdownlint', 'mdl', 'proselint', 'redpen', 'textlint', 'vale',
    'writegood',
  },
  nroff = {'alex', 'proselint', 'writegood'},
  objc = {'clang'},
  objcpp = {'clang'},
  php = {'phpcs', 'phpstan'},
  po = {'alex', 'proselint', 'writegood'},
  pod = {'alex', 'proselint', 'writegood'},
  python = {'flake8', 'mypy', 'pycodestyle', 'pydocstyle', 'pyflakes', 'pylint'},
  rst = {'alex', 'proselint', 'redpen', 'rstcheck', 'textlint', 'vale', 'writegood'},
  rust = {'cargo'},
  sass = {'sasslint', 'stylelint'},
  scss = {'sasslint', 'stylelint'},
  sh = {'bashate', 'shellcheck'},
  sql = {'sqlint'},
  stylus = {'stylelint'},
  sugarss = {'stylelint'},
  teal = {'tlcheck'},
  tex = {'alex', 'proselint', 'redpen', 'textlint', 'vale', 'writegood'},
  texinfo = {'alex', 'proselint', 'writegood'},
  typescript = {'eslint', 'standard', 'tslint', 'typecheck', 'xo'},
  vim = {'vint'},
  vimwiki = {'alex', 'languagetool', 'proselint', 'markdownlint', 'mdl', 'remark-lint', 'writegood'},
  vue = {'eslint'},
  xhtml = {'alex', 'proselint', 'writegood'},
  xsd = {'xmllint'},
  xml = {'xmllint'},
  xslt = {'xmllint'},
  yaml = {'spectral', 'yamllint'},
  zsh = {'shell'},
}
require('user.cleanup.ale')
